In [1]:
import cv2

In [2]:
img = cv2.imread("pics/peace.jpeg" ,0) #0 greyscale
img_c = cv2.imread("pics/peace.jpeg" ,1) #0 greyscale

img

array([[137, 137, 137, ..., 136, 136, 137],
       [138, 138, 138, ..., 137, 137, 138],
       [139, 139, 139, ..., 139, 139, 140],
       ...,
       [ 89,  95,  98, ..., 107, 105, 103],
       [ 68,  73,  75, ..., 126, 118, 111],
       [ 58,  59,  58, ..., 129, 117, 108]], dtype=uint8)

In [3]:
print(type(img))

<class 'numpy.ndarray'>


In [4]:
print(img)

[[137 137 137 ... 136 136 137]
 [138 138 138 ... 137 137 138]
 [139 139 139 ... 139 139 140]
 ...
 [ 89  95  98 ... 107 105 103]
 [ 68  73  75 ... 126 118 111]
 [ 58  59  58 ... 129 117 108]]


In [5]:
img.shape
img.ndim

2

In [6]:
img_c.ndim

3

In [7]:
# cv2.imshow("peace", img_c)
# cv2.waitKey(0) # time , o

In [ ]:
resized = cv2.resize(img, (500,500))
cv2.imshow("resizedpeace" ,resized)
cv2.waitKey(0)