In [1]:
import pandas as pd
import numpy as np
import cv2

In [2]:
img_0 = cv2.imread("pics/smallgray.png" ,0) #0 greyscale
img_0

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
img_1 = cv2.imread("pics/smallgray.png" ,1) #1 rgb
img_1

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [4]:
type(img_1)

numpy.ndarray

In [6]:
cv2.imwrite("pics/newsmallgray.png",img_0)

True

In [9]:
img_0[0:1,0:2]
#row int, col inter

array([[187, 158]], dtype=uint8)

In [10]:
for i in img_0:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [11]:
for i in img_0.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [13]:
imgs= np.hstack( (img_0,img_0) )
imgs

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
imgs= np.vstack( (img_0,img_0) )
imgs

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
#hsplit, vsplit 